#起应用名称
spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.0.6
    port: 5672
    username: root
    password: root
  cloud:
    config:
      override-none: true #覆盖项目的application.yml配置文件

#设置端口号
#server:
#  port: 8001

  
#添加 Eureka 服务器的地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
#配置1      
---
spring:
  profiles: item1

server:
  port: 8001


#配置2
---     
spring:
  profiles: item2
      
server:
  port: 8002
      
      
      
      
      